name: Training Pipeline

on: [push]

jobs:
  training:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow metaflow scikit-learn pandas numpy keras "jax[cpu]" python-dotenv

    - name: Start MLflow
      run: |
        mlflow server --host 127.0.0.1 --port 5000 &
        sleep 5

    - name: Run training
      env:
        MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        KERAS_BACKEND: jax
      run: python training.py run --accuracy-threshold 0.7

    - name: Save artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: training-artifacts
        path: |
          .metaflow/
          mlruns/
          *.log
