name: Training Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '.github/workflows/training-pipeline.yml'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start MLflow server
        run: |
          mlflow server --host 127.0.0.1 --port 5000 &
          sleep 5

      - name: Run Training Pipeline
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
          KERAS_BACKEND: jax
        run: |
          python training.py run --accuracy-threshold 0.7

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: training-artifacts
          path: |
            .metaflow/
            mlruns/
            *.log
          retention-days: 7