name: Training Pipeline

on: 
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow
          pip install mlflow metaflow scikit-learn pandas numpy keras python-dotenv

      - name: Verify repository contents
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Create test script
        run: |
          echo "import mlflow
          import pandas as pd
          import numpy as np
          from sklearn.model_selection import train_test_split
          
          data = pd.DataFrame({
              'feature': np.random.rand(100),
              'target': np.random.choice(['A', 'B'], 100)
          })
          
          X_train, X_test, y_train, y_test = train_test_split(
              data['feature'].values.reshape(-1, 1),
              data['target'],
              test_size=0.2
          )
          
          with mlflow.start_run():
              mlflow.log_param('test_size', 0.2)
              mlflow.log_metric('samples', len(data))
              print('Training completed successfully!')" > test_training.py

      - name: Start MLflow server
        run: |
          python -m mlflow server --host 127.0.0.1 --port 5000 &
          sleep 5

      - name: Run test script
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        run: |
          python test_training.py

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: training-artifacts
          path: |
            .metaflow/
            mlruns/
            *.log
            *.py