name: Training Pipeline Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install MLflow
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Test MLflow
        run: |
          python -c "import mlflow; print('MLflow version:', mlflow.__version__)"
          python -m mlflow --version

      - name: Test MLflow server
        run: |
          python -m mlflow server --host 127.0.0.1 --port 5000 &
          sleep 5
          curl http://127.0.0.1:5000